import { describe, expect, it, vi } from 'vitest'
import {
  deleteLectureBlocks,
  deleteLectureRecord,
  fetchLectureRecords,
  insertLectureBlock,
  insertLectureRecord,
  updateLectureCompletion,
} from '../lectureService'

const createBuilder = (result) => {
  const builder = {
    select: vi.fn(() => builder),
    eq: vi.fn(() => builder),
    order: vi.fn(() => builder),
    insert: vi.fn(() => builder),
    update: vi.fn(() => builder),
    delete: vi.fn(() => builder),
    single: vi.fn().mockResolvedValue(result),
    then: (resolve, reject) =>
      Promise.resolve(result).then(resolve, reject),
  }

  return builder
}

const createSupabase = (builders) => ({
  from: vi.fn((table) => builders[table]),
})

describe('lectureService', () => {
  it('fetches lectures and matching lecture blocks', async () => {
    const lectureResult = {
      data: [{ id: 'lecture-1' }],
      error: null,
    }
    const blockResult = {
      data: [{ id: 'block-1' }],
      error: null,
    }
    const lectureBuilder = createBuilder(lectureResult)
    const blockBuilder = createBuilder(blockResult)
    const supabase = createSupabase({
      lectures: lectureBuilder,
      time_blocks: blockBuilder,
    })

    await expect(
      fetchLectureRecords({
        supabase,
        userId: 'user-1',
        classId: 'class-1',
      }),
    ).resolves.toEqual({
      lectures: lectureResult.data,
      blocks: blockResult.data,
    })

    expect(lectureBuilder.eq).toHaveBeenCalledWith(
      'user_id',
      'user-1',
    )
    expect(lectureBuilder.eq).toHaveBeenCalledWith(
      'class_id',
      'class-1',
    )
    expect(blockBuilder.eq).toHaveBeenCalledWith(
      'block_type',
      'Lecture',
    )
  })

  it('throws when either fetch fails', async () => {
    const expectedError = new Error('Lecture query failed')
    const supabase = createSupabase({
      lectures: createBuilder({
        data: null,
        error: expectedError,
      }),
      time_blocks: createBuilder({
        data: [],
        error: null,
      }),
    })

    await expect(
      fetchLectureRecords({
        supabase,
        userId: 'user-1',
        classId: 'class-1',
      }),
    ).rejects.toBe(expectedError)
  })

  it('inserts a lecture with normalised database fields', async () => {
    const created = { id: 'lecture-1' }
    const builder = createBuilder({
      data: created,
      error: null,
    })
    const supabase = createSupabase({ lectures: builder })

    await expect(
      insertLectureRecord({
        supabase,
        userId: 'user-1',
        classId: 'class-1',
        title: 'Lecture 1',
        lectureUrl: null,
        weekNumber: 1,
        estimatedMinutes: 90,
      }),
    ).resolves.toBe(created)

    expect(builder.insert).toHaveBeenCalledWith({
      user_id: 'user-1',
      class_id: 'class-1',
      title: 'Lecture 1',
      lecture_url: null,
      week_number: 1,
      estimated_minutes: 90,
      completed: false,
      completed_at: null,
    })
  })

  it('sets and clears completed_at with completion state', async () => {
    vi.useFakeTimers()
    vi.setSystemTime(
      new Date('2026-07-28T14:30:00.000Z'),
    )

    const builder = createBuilder({
      data: { id: 'lecture-1' },
      error: null,
    })
    const supabase = createSupabase({ lectures: builder })

    await updateLectureCompletion({
      supabase,
      userId: 'user-1',
      lectureId: 'lecture-1',
      completed: true,
    })

    expect(builder.update).toHaveBeenCalledWith({
      completed: true,
      completed_at: '2026-07-28T14:30:00.000Z',
    })

    vi.useRealTimers()
  })

  it('inserts a timetable block linked to its lecture', async () => {
    const builder = createBuilder({
      data: { id: 'block-1' },
      error: null,
    })
    const supabase = createSupabase({
      time_blocks: builder,
    })

    await insertLectureBlock({
      supabase,
      userId: 'user-1',
      classId: 'class-1',
      lectureId: 'lecture-1',
      title: 'Lecture 1',
      formData: {
        block_date: '2026-07-30',
        start_time: '10:00',
        end_time: '11:00',
      },
      completed: false,
      autoGenerated: true,
    })

    expect(builder.insert).toHaveBeenCalledWith(
      expect.objectContaining({
        lecture_id: 'lecture-1',
        block_type: 'Lecture',
        auto_generated: true,
        recurrence_type: 'none',
      }),
    )
  })

  it('deletes blocks before the lecture when called in that order', async () => {
    const blockBuilder = createBuilder({ error: null })
    const lectureBuilder = createBuilder({ error: null })
    const supabase = createSupabase({
      time_blocks: blockBuilder,
      lectures: lectureBuilder,
    })

    await deleteLectureBlocks({
      supabase,
      userId: 'user-1',
      lectureId: 'lecture-1',
    })
    await deleteLectureRecord({
      supabase,
      userId: 'user-1',
      lectureId: 'lecture-1',
    })

    expect(blockBuilder.delete).toHaveBeenCalledOnce()
    expect(blockBuilder.eq).toHaveBeenCalledWith(
      'lecture_id',
      'lecture-1',
    )
    expect(lectureBuilder.delete).toHaveBeenCalledOnce()
  })
})
