const LECTURE_FIELDS = `
  id,
  user_id,
  class_id,
  title,
  lecture_url,
  week_number,
  estimated_minutes,
  completed,
  completed_at,
  created_at
`

const TIME_BLOCK_FIELDS = `
  id,
  user_id,
  class_id,
  coursework_id,
  title,
  block_date,
  start_time,
  end_time,
  block_type,
  is_recurring,
  recurrence_type,
  recurrence_end_date,
  auto_generated,
  lecture_id,
  completed,
  created_at
`

const throwIfError = (error) => {
  if (error) {
    throw error
  }
}

export const fetchLectureRecords = async ({
  supabase,
  userId,
  classId,
}) => {
  const [lecturesResult, blocksResult] =
    await Promise.all([
      supabase
        .from('lectures')
        .select(LECTURE_FIELDS)
        .eq('user_id', userId)
        .eq('class_id', classId)
        .order('week_number', {
          ascending: true,
        }),

      supabase
        .from('time_blocks')
        .select(TIME_BLOCK_FIELDS)
        .eq('user_id', userId)
        .eq('class_id', classId)
        .eq('block_type', 'Lecture')
        .order('block_date', {
          ascending: true,
        })
        .order('start_time', {
          ascending: true,
        }),
    ])

  throwIfError(lecturesResult.error)
  throwIfError(blocksResult.error)

  return {
    lectures: lecturesResult.data,
    blocks: blocksResult.data,
  }
}

export const insertLectureRecord = async ({
  supabase,
  userId,
  classId,
  title,
  lectureUrl,
  weekNumber,
  estimatedMinutes,
}) => {
  const { data, error } = await supabase
    .from('lectures')
    .insert({
      user_id: userId,
      class_id: classId,
      title,
      lecture_url: lectureUrl,
      week_number: weekNumber,
      estimated_minutes: estimatedMinutes,
      completed: false,
      completed_at: null,
    })
    .select(LECTURE_FIELDS)
    .single()

  throwIfError(error)
  return data
}

export const updateLectureRecord = async ({
  supabase,
  userId,
  lectureId,
  title,
  lectureUrl,
  weekNumber,
  estimatedMinutes,
}) => {
  const { data, error } = await supabase
    .from('lectures')
    .update({
      title,
      lecture_url: lectureUrl,
      week_number: weekNumber,
      estimated_minutes: estimatedMinutes,
    })
    .eq('id', lectureId)
    .eq('user_id', userId)
    .select(LECTURE_FIELDS)
    .single()

  throwIfError(error)
  return data
}

export const updateLectureCompletion = async ({
  supabase,
  userId,
  lectureId,
  completed,
}) => {
  const { data, error } = await supabase
    .from('lectures')
    .update({
      completed,
      completed_at: completed
        ? new Date().toISOString()
        : null,
    })
    .eq('id', lectureId)
    .eq('user_id', userId)
    .select(LECTURE_FIELDS)
    .single()

  throwIfError(error)
  return data
}

export const insertLectureBlock = async ({
  supabase,
  userId,
  classId,
  lectureId,
  title,
  formData,
  completed = false,
  autoGenerated = false,
}) => {
  const { data, error } = await supabase
    .from('time_blocks')
    .insert({
      user_id: userId,
      class_id: classId,
      coursework_id: null,
      title,
      block_date: formData.block_date,
      start_time: formData.start_time,
      end_time: formData.end_time,
      block_type: 'Lecture',
      is_recurring: false,
      recurrence_type: 'none',
      recurrence_end_date: null,
      auto_generated: autoGenerated,
      lecture_id: lectureId,
      completed,
    })
    .select(TIME_BLOCK_FIELDS)
    .single()

  throwIfError(error)
  return data
}

export const updateLectureBlock = async ({
  supabase,
  userId,
  blockId,
  title,
  formData,
}) => {
  const { data, error } = await supabase
    .from('time_blocks')
    .update({
      title,
      block_date: formData.block_date,
      start_time: formData.start_time,
      end_time: formData.end_time,
    })
    .eq('id', blockId)
    .eq('user_id', userId)
    .select(TIME_BLOCK_FIELDS)
    .single()

  throwIfError(error)
  return data
}

export const updateLectureBlockCompletion =
  async ({
    supabase,
    userId,
    blockId,
    completed,
  }) => {
    const { data, error } = await supabase
      .from('time_blocks')
      .update({ completed })
      .eq('id', blockId)
      .eq('user_id', userId)
      .select(TIME_BLOCK_FIELDS)
      .single()

    throwIfError(error)
    return data
  }

export const deleteLectureBlockById = async ({
  supabase,
  userId,
  blockId,
}) => {
  const { error } = await supabase
    .from('time_blocks')
    .delete()
    .eq('id', blockId)
    .eq('user_id', userId)

  throwIfError(error)
}

export const deleteLectureBlocks = async ({
  supabase,
  userId,
  lectureId,
}) => {
  const { error } = await supabase
    .from('time_blocks')
    .delete()
    .eq('lecture_id', lectureId)
    .eq('user_id', userId)

  throwIfError(error)
}

export const deleteLectureRecord = async ({
  supabase,
  userId,
  lectureId,
}) => {
  const { error } = await supabase
    .from('lectures')
    .delete()
    .eq('id', lectureId)
    .eq('user_id', userId)

  throwIfError(error)
}
