import {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from 'react'
import { supabase } from '../lib/supabaseClient'
import {
  getAuthenticatedUser,
  getErrorMessage,
} from './hookUtils'
import {
  getLectureCollections,
  hasCompleteTimeBlock,
  mergeLecturesWithBlocks,
  mergeLectureWithBlock,
  prepareLectureValues,
  sortLectures,
} from './lectureHelpers'
import {
  deleteLectureBlockById,
  deleteLectureBlocks,
  deleteLectureRecord,
  fetchLectureRecords,
  insertLectureBlock,
  insertLectureRecord,
  updateLectureBlock,
  updateLectureBlockCompletion,
  updateLectureCompletion,
  updateLectureRecord,
} from './lectureService'

const useClassLectures = (
  classId,
  { fetchOnMount = true } = {},
) => {
  const [lectures, setLectures] = useState([])
  const [loading, setLoading] = useState(
    fetchOnMount,
  )
  const [error, setError] = useState(null)

  const getCurrentUser = useCallback(
    () =>
      getAuthenticatedUser(
        supabase,
        'You must be signed in to manage lectures.',
      ),
    [],
  )

  const handleError = useCallback(
    (caughtError) => {
      const message = getErrorMessage(
        caughtError,
        'Something went wrong while managing lectures.',
      )

      setError(message)
      return caughtError
    },
    [],
  )

  const fetchLectures = useCallback(async () => {
    if (!classId) {
      setLectures([])
      setLoading(false)
      setError('A class ID is required.')
      return []
    }

    setLoading(true)
    setError(null)

    try {
      const user = await getCurrentUser()
      const records = await fetchLectureRecords({
        supabase,
        userId: user.id,
        classId,
      })

      const mergedLectures =
        mergeLecturesWithBlocks(
          records.lectures,
          records.blocks,
        )

      setLectures(mergedLectures)
      return mergedLectures
    } catch (fetchError) {
      setLectures([])
      handleError(fetchError)
      throw fetchError
    } finally {
      setLoading(false)
    }
  }, [
    classId,
    getCurrentUser,
    handleError,
  ])

  useEffect(() => {
    if (!fetchOnMount) {
      return
    }

    fetchLectures().catch(() => {
      // Error state is already handled.
    })
  }, [fetchOnMount, fetchLectures])

  const createLecture = useCallback(
    async (formData) => {
      setError(null)

      if (!classId) {
        const idError = new Error(
          'A class ID is required to create a lecture.',
        )

        handleError(idError)
        throw idError
      }

      try {
        const user = await getCurrentUser()
        const values = prepareLectureValues(
          formData,
          90,
        )

        const createdLecture =
          await insertLectureRecord({
            supabase,
            userId: user.id,
            classId,
            title: values.title,
            lectureUrl: values.lectureUrl,
            weekNumber: values.weekNumber,
            estimatedMinutes:
              values.estimatedMinutes,
          })

        let createdBlock = null

        if (hasCompleteTimeBlock(formData)) {
          try {
            createdBlock =
              await insertLectureBlock({
                supabase,
                userId: user.id,
                classId,
                lectureId: createdLecture.id,
                title: values.title,
                formData,
                completed: false,
                autoGenerated:
                  formData.auto_generated ||
                  false,
              })
          } catch (blockError) {
            try {
              await deleteLectureRecord({
                supabase,
                userId: user.id,
                lectureId: createdLecture.id,
              })
            } catch {
              // Preserve the original block error.
            }

            throw blockError
          }
        }

        const mergedLecture =
          mergeLectureWithBlock(
            createdLecture,
            createdBlock,
          )

        setLectures(
          (previousLectures) =>
            sortLectures([
              ...previousLectures,
              mergedLecture,
            ]),
        )

        return mergedLecture
      } catch (createError) {
        handleError(createError)
        throw createError
      }
    },
    [
      classId,
      getCurrentUser,
      handleError,
    ],
  )

  const updateLecture = useCallback(
    async (lectureId, formData) => {
      setError(null)

      if (!lectureId) {
        const idError = new Error(
          'A lecture ID is required to update a lecture.',
        )

        handleError(idError)
        throw idError
      }

      try {
        const user = await getCurrentUser()
        const currentLecture = lectures.find(
          (lecture) =>
            lecture.id === lectureId,
        )

        if (!currentLecture) {
          throw new Error(
            'Lecture could not be found.',
          )
        }

        const values = prepareLectureValues(
          formData,
          currentLecture.estimated_minutes,
        )

        const updatedLecture =
          await updateLectureRecord({
            supabase,
            userId: user.id,
            lectureId,
            title: values.title,
            lectureUrl: values.lectureUrl,
            weekNumber: values.weekNumber,
            estimatedMinutes:
              values.estimatedMinutes,
          })

        const hasTimeBlock =
          hasCompleteTimeBlock(formData)
        let updatedBlock =
          currentLecture.timeBlock

        if (
          currentLecture.timeBlock &&
          hasTimeBlock
        ) {
          updatedBlock =
            await updateLectureBlock({
              supabase,
              userId: user.id,
              blockId:
                currentLecture.timeBlock.id,
              title: values.title,
              formData,
            })
        } else if (
          !currentLecture.timeBlock &&
          hasTimeBlock
        ) {
          updatedBlock =
            await insertLectureBlock({
              supabase,
              userId: user.id,
              classId,
              lectureId,
              title: values.title,
              formData,
              completed:
                currentLecture.completed,
              autoGenerated: false,
            })
        } else if (
          currentLecture.timeBlock &&
          !hasTimeBlock
        ) {
          await deleteLectureBlockById({
            supabase,
            userId: user.id,
            blockId:
              currentLecture.timeBlock.id,
          })

          updatedBlock = null
        }

        const mergedLecture =
          mergeLectureWithBlock(
            updatedLecture,
            updatedBlock,
          )

        setLectures(
          (previousLectures) =>
            sortLectures(
              previousLectures.map(
                (lecture) =>
                  lecture.id === lectureId
                    ? mergedLecture
                    : lecture,
              ),
            ),
        )

        return mergedLecture
      } catch (updateError) {
        handleError(updateError)
        throw updateError
      }
    },
    [
      classId,
      getCurrentUser,
      handleError,
      lectures,
    ],
  )

  const toggleLectureComplete =
    useCallback(
      async (lectureId) => {
        setError(null)

        try {
          const user =
            await getCurrentUser()

          const currentLecture =
            lectures.find(
              (lecture) =>
                lecture.id === lectureId,
            )

          if (!currentLecture) {
            throw new Error(
              'Lecture could not be found.',
            )
          }

          const nextCompleted =
            !currentLecture.completed

          const updatedLecture =
            await updateLectureCompletion({
              supabase,
              userId: user.id,
              lectureId,
              completed: nextCompleted,
            })

          let updatedBlock =
            currentLecture.timeBlock

          if (currentLecture.timeBlock) {
            updatedBlock =
              await updateLectureBlockCompletion({
                supabase,
                userId: user.id,
                blockId:
                  currentLecture.timeBlock.id,
                completed: nextCompleted,
              })
          }

          const mergedLecture =
            mergeLectureWithBlock(
              updatedLecture,
              updatedBlock,
            )

          setLectures(
            (previousLectures) =>
              previousLectures.map(
                (lecture) =>
                  lecture.id === lectureId
                    ? mergedLecture
                    : lecture,
              ),
          )

          return mergedLecture
        } catch (toggleError) {
          handleError(toggleError)
          throw toggleError
        }
      },
      [
        getCurrentUser,
        handleError,
        lectures,
      ],
    )

  const deleteLecture = useCallback(
    async (lectureId) => {
      setError(null)

      if (!lectureId) {
        const idError = new Error(
          'A lecture ID is required to delete a lecture.',
        )

        handleError(idError)
        throw idError
      }

      try {
        const user = await getCurrentUser()

        await deleteLectureBlocks({
          supabase,
          userId: user.id,
          lectureId,
        })

        await deleteLectureRecord({
          supabase,
          userId: user.id,
          lectureId,
        })

        setLectures(
          (previousLectures) =>
            previousLectures.filter(
              (lecture) =>
                lecture.id !== lectureId,
            ),
        )
      } catch (deleteError) {
        handleError(deleteError)
        throw deleteError
      }
    },
    [getCurrentUser, handleError],
  )

  const lectureCollections = useMemo(
    () => getLectureCollections(lectures),
    [lectures],
  )

  return {
    lectures,
    nextLecture:
      lectureCollections.nextLecture,
    completedLectures:
      lectureCollections.completedLectures,
    upcomingLectures:
      lectureCollections.upcomingLectures,
    loading,
    error,
    setError,
    fetchLectures,
    createLecture,
    updateLecture,
    toggleLectureComplete,
    deleteLecture,
  }
}

export default useClassLectures
